// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func About() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"about\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Hi, I'm Tino`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `I try to help myself write better code.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Until now`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div class=\"about-sentences\"><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `I did a one year course in IT in 2017 where I got introduced to Ruby, Sinatra and Rails. `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `After graduating I got hired by Age Partnership in Leeds, UK and have been a c# desktop app developer since.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `I enjoy learning new things and technologies. `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `Currently on a journey to explore go and htmx.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := `Hoping future endeavours to inlcude C, Erlang, Clojure, Scala, jq, sed`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"about-sentence\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := `I've worked with a wide range of technologies, despite my main focus being .NET`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var11 := `Most of the other technologies have been used as a one off project at the company or as a learning and experimental experience in my free time`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var12 := `Tools`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div class=\"tech-images\"><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var13 := `Web`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/html.png\" alt=\"HTML\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/css.png\" alt=\"CSS\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/react.png\" alt=\"React\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/bootstrap.png\" alt=\"Bootstrap\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var14 := `Desktop`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/winforms.png\" alt=\"WinForms\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/wpf.png\" alt=\"WPF\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/ltk.png\" alt=\"LTK\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var15 := `Queue`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/rabbitmq.png\" alt=\"RabbitMQ\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var16 := `Mobile`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/travolta.gif\" alt=\"Travolta\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var17 := `Database`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/mongodb.png\" alt=\"MongoDB\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/sql.png\" alt=\"SQL\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var18 := `Version Control`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/git.png\" alt=\"Git\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var19 := `OS`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var19)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/linux.png\" alt=\"Linux\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/windows.png\" alt=\"Windows\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var20 := `Languages`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/csharp.png\" alt=\"C#\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/go.png\" alt=\"Go\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/lisp.png\" alt=\"Lisp\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/javascript.png\" alt=\"JavaScript\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/ruby.png\" alt=\"Ruby\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var21 := `Code Editor`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var21)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/vim.png\" alt=\"Vim\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/neovim.png\" alt=\"neovim\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/vs.png\" alt=\"Vs\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/vscode.png\" alt=\"VsCode\"></div></div><div class=\"tech-image-group\"><div class=\"tech-image-group-title\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var22 := `Terminal`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var22)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</em></div><div class=\"tech-image-group-items\"><img class=\"tech-image\" src=\"/assets/img/about/tech/wterm.png\" alt=\"Windows Terminal\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/git.png\" alt=\"Git Bash\"> <img class=\"tech-image\" src=\"/assets/img/about/tech/zsh.png\" alt=\"Zsh\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
